version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-fast-deployments"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1riu5nh0yhrxr"
s3_prefix = "sam-fast-deployments"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
